Repository cocodaeng/cocodaeng-back, pull requests merged in 2023-10, with the labels that each got.

#13 [FEATURE] - [MAIN] 홈 화면 데이터 조회 기능 구현
  app.js
  package-lock.json
  src/controllers/diary/diary-controller.js
  src/controllers/main/main-controller.js
  src/controllers/pet/pet-program-controller.js
  src/database/diary/diary-query.js
  src/database/main/main-query.js
  src/database/pet/pet-program-query.js
  src/dto/diary-dto.js
  src/dto/pet-program-dto.js
  src/repositories/diary/diary-repository.js
  src/repositories/main/main-repository.js
  src/repositories/pet/pet-program-repository.js
  src/routes/main-route.js
  src/routes/pet-route.js
  src/services/diary/diary-service.js
  src/services/main/main-service.js
  src/services/pet/pet-program-service.js
Labels: ✨ Feature

#16 [FEATURE] - [PETPROGRAM] 식재료 탐험 페이지 조회하는 기능 구현
  src/apis/oauth/kakao-api.js
  src/config/db-config.js
  src/controllers/diary/diary-controller.js
  src/controllers/main/food-exploration-controller.js
  src/controllers/main/main-controller.js
  src/controllers/member/member-controller.js
  src/controllers/oauth/kakao-controller.js
  src/controllers/pet/pet-controller.js
  src/controllers/pet/pet-program-controller.js
  src/database/connection.js
  src/database/diary/diary-query.js
  src/database/main/food-exploration-query.js
  src/database/main/main-query.js
  src/database/member/member-query.js
  src/database/pet/pet-program-query.js
  src/database/pet/pet-query.js
  src/middleware/auth-middleware.js
  src/repositories/diary/diary-repository.js
  src/repositories/main/food-exploration-repository.js
  src/repositories/main/main-repository.js
  src/repositories/member/member-repository.js
  src/repositories/pet/pet-program-repository.js
  src/repositories/pet/pet-repository.js
  src/routes/apple-route.js
  src/routes/kakao-route.js
  src/routes/main-route.js
  src/routes/member-route.js
  src/routes/pet-route.js
  src/services/diary/diary-service.js
  src/services/main/food-exploration-service.js
  src/services/main/main-service.js
  src/services/member/member-service.js
  src/services/oauth/kakao-service.js
  src/services/pet/pet-program-service.js
  src/services/pet/pet-service.js
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#18 [Feature] -{DIARY} 다이어리 CRUD 기능 구현
  app.js
  package-lock.json
  package.json
  src/controllers/allergy/allergy-controller.js
  src/controllers/diary/diary-controller.js
  src/controllers/main/food-exploration-controller.js
  src/controllers/main/main-controller.js
  src/controllers/member/member-controller.js
  src/controllers/member/policy-controller.js
  src/controllers/pet/bread-controller.js
  src/database/allergy/allergy-query.js
  src/database/diary/diary-query.js
  src/database/main/main-query.js
  src/database/member/member-query.js
  src/database/member/policy-query.js
  src/database/pet/pet-query.js
  src/dto/diary/diary-dto.js
  src/dto/pet/request/pet-request-dto.js
  src/middleware/auth-middleware.js
  src/repositories/allergy/allergy-repository.js
  src/repositories/diary/diary-repository.js
  src/repositories/main/main-repository.js
  src/repositories/member/member-repository.js
  src/repositories/member/policy-repository.js
  src/repositories/pet/pet-repository.js
  src/routes/apple-route.js
  src/routes/diary-route.js
  src/routes/member-route.js
  src/routes/pet-route.js
  src/services/allergy/allergy-service.js
  src/services/diary/diary-service.js
  src/services/main/food-exploration-service.js
  src/services/main/main-service.js
  src/services/member/member-service.js
  src/services/member/policy-service.js
  src/utils/image-uploader.js
Labels: ✨ Feature

#20 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📃 Docs

#22 refactor: 에러 핸들링 적용
  app.js
  src/controllers/allergy/allergy-controller.js
  src/controllers/diary/diary-controller.js
  src/controllers/main/food-exploration-controller.js
  src/controllers/main/main-controller.js
  src/controllers/member/member-controller.js
  src/controllers/member/policy-controller.js
  src/controllers/oauth/kakao-controller.js
  src/controllers/pet/bread-controller.js
  src/controllers/pet/pet-controller.js
  src/controllers/pet/pet-program-controller.js
  src/database/pet/bread-query.js
  src/database/pet/pet-program-query.js
  src/database/pet/pet-query.js
  src/repositories/diary/diary-repository.js
  src/repositories/main/food-exploration-repository.js
  src/repositories/main/main-repository.js
  src/repositories/member/member-repository.js
  src/repositories/member/policy-repository.js
  src/repositories/pet/bread-repository.js
  src/repositories/pet/pet-program-repository.js
  src/repositories/pet/pet-repository.js
  src/routes/main-route.js
  src/routes/member-route.js
  src/routes/pet-route.js
  src/services/allergy/allergy-service.js
  src/services/diary/diary-service.js
  src/services/main/food-exploration-service.js
  src/services/main/main-service.js
  src/services/member/member-service.js
  src/services/member/policy-service.js
  src/services/pet/bread-service.js
  src/services/pet/pet-program-service.js
  src/services/pet/pet-service.js
  src/utils/image-uploader.js
  src/utils/jwt-decoder.js
Labels: 🔨 Refactor

#25 [FEATURE] - [PET_PROGRAM] 기/미 참여 프로그램 페이지 조회 기능 구현
  src/controllers/main/food-exploration-controller.js
  src/database/allergy/allergy-query.js
  src/database/diary/diary-query.js
  src/database/main/food-exploration-query.js
  src/database/main/main-query.js
  src/database/member/member-query.js
  src/database/member/policy-query.js
  src/database/oauth/apple-query.js
  src/database/oauth/kakao-query.js
  src/database/pet/bread-query.js
  src/database/pet/pet-program-query.js
  src/database/pet/pet-query.js
  src/repositories/main/food-exploration-repository.js
  src/repositories/oauth/apple-repository.js
  src/repositories/oauth/kakao-repository.js
  src/routes/main-route.js
  src/services/main/food-exploration-service.js
  src/services/main/main-service.js
  src/services/pet/pet-service.js
Labels: 📬 API, ✨ Feature, 🔨 Refactor
